site_name: Jupyter to Medium
site_description: Publish a Jupyter Notebook as a Medium blog post
site_author: Ted Petrou
site_url: https://www.dexplo.org/jupyter_to_medium
repo_url: https://github.com/dexplo/jupyter_to_medium
copyright: Copyright @ 2020 Ted Petrou
google_analytics:
  - UA-119777567-7
  - dexplo.org

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - tabs

nav:
  - Home: index.md
  - What's New: whats_new.md
  - Dexplo Libraries:
    - Dexplo: https://www.dexplo.org

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dexplo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TedPetrou
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/TedPetrou
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dunderdata
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dunderdata

markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - codehilite:
        guess_lang: false

plugins:
    - search
    - macros
    - minify:
        minify_html: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
